# Generated by Django 4.2.4 on 2023-08-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_product_connection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=60)),
                ('comment', models.CharField(max_length=350)),
                ('grade', models.FloatField(default=0, max_length=5.0)),
                ('create_data', models.DateTimeField(auto_now_add=True)),
                ('modification_data', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
