# Generated by Django 4.2.4 on 2023-08-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='connection_review',
            field=models.ManyToManyField(related_name='connection_review', to='posts.review'),
        ),
    ]
